// Generated by CoffeeScript 1.3.3
(function() {
  var ResourceCache;

  ResourceCache = (function() {

    function ResourceCache() {}

    ResourceCache.prototype.store_objects = function(path, objects) {
      /* Stores resulting objects in cache.
      
      **Arguments:**
      
      - `path` Path object that will be used to identify a request.
      E.g.: `{method: 'get', path: '/users/list'}`
      - `objects` Resulting objects formatted as array of objects.
      E.g.: `[{name: 'foo', age: 20}, {name: 'bar', age: 21}]`
      Objects should also contain value for the `id` field.
      */

      var object, object_keys, request_key;
      object_keys = (function() {
        var _i, _len, _results;
        _results = [];
        for (_i = 0, _len = objects.length; _i < _len; _i++) {
          object = objects[_i];
          _results.push(this._store_object(object));
        }
        return _results;
      }).call(this);
      request_key = this._object_checksum(path);
      request_key = "a.cache.request." + request_key;
      return localStorage[request_key] = JSON.stringify(object_keys);
    };

    ResourceCache.prototype._store_object = function(object) {
      var key;
      key = object.id || this._object_checksum(object);
      key = "a.cache.object." + key;
      localStorage[key] = JSON.stringify(object);
      return key;
    };

    ResourceCache.prototype._object_checksum = function(object) {
      var acc, i, text, _i, _ref;
      text = JSON.stringify(object);
      acc = 1;
      for (i = _i = 0, _ref = text.length; 0 <= _ref ? _i < _ref : _i > _ref; i = 0 <= _ref ? ++_i : --_i) {
        acc *= text[i].charCodeAt(0);
      }
      return acc % 1000000000;
    };

    return ResourceCache;

  })();

  module.exports = ResourceCache;

}).call(this);
