// Generated by CoffeeScript 1.3.3
(function() {
  var Atmos, Spine,
    __slice = [].slice;

  Spine = require('spine');

  Atmos = require('./atmos');

  Spine.Model.Atmos = {
    extended: function() {
      var spineSave;
      spineSave = this.prototype["save"];
      this.prototype["save"] = function() {
        var args, atmos, options;
        args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
        atmos = Atmos.instance;
        options = args[0];
        if ((atmos != null) && (options != null) && options.remote === true) {
          return atmos.save(this, options);
        } else {
          return spineSave.call.apply(spineSave, [this].concat(__slice.call(args)));
        }
      };
      this.prototype["changeID"] = function(id) {
        this.destroy();
        this.id = id;
        this.newRecord = true;
        return this.save();
      };
      return this.bind('beforeCreate', function(record) {
        return record.id || (record.id = this._uuid());
      });
    },
    _uuid: function() {
      return 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, function(c) {
        var r, v;
        r = Math.random() * 16 | 0;
        v = c === 'x' ? r : r & 3 | 8;
        return v.toString(16);
      });
    },
    sync: function(params) {
      var atmos,
        _this = this;
      if (params == null) {
        params = {};
      }
      this.fetch();
      atmos = Atmos.instance;
      return atmos.fetch(this.className, params, function(objects) {
        console.log('spine.atmos: finished fetch', objects);
        console.log('loading objects to class', objects, _this);
        return _this.refresh(objects);
      });
    }
  };

}).call(this);
