// Generated by CoffeeScript 1.3.1
(function() {
  var AppContext, MessageClient, ResourceClient, SocketIO, Spine, Synchronizer,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor; child.__super__ = parent.prototype; return child; },
    __slice = [].slice;

  Spine = require('spine');

  SocketIO = require('./vendor/socket.io');

  window.SocketIO = SocketIO;

  MessageClient = require('./message_client');

  AppContext = require('./app_context');

  ResourceClient = require('./resource_client');

  Synchronizer = (function(_super) {

    __extends(Synchronizer, _super);

    Synchronizer.name = 'Synchronizer';

    Synchronizer.include(Spine.Events);

    function Synchronizer(options) {
      this.messageClient = new MessageClient(this);
      this.appContext = new AppContext();
      this.resourceClient = new ResourceClient({
        sync: this,
        appContext: this.appContext
      });
      this._needsSync = false;
      this._isSyncInProgress = false;
      Synchronizer.instance = this;
      Synchronizer.res = this.resourceClient;
    }

    Synchronizer.prototype.updateOrCreate = function(uri, item) {
      if (item.id && item.id !== uri.id) {
        console.log("changing id " + uri.id + " -> " + item.id);
        this.appContext.changeID(uri, item.id);
        uri.id = item.id;
      }
      return this.appContext.updateOrCreate(uri, item);
    };

    Synchronizer.prototype.fetch = function() {
      var params, _ref;
      params = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
      return (_ref = this.resourceClient).fetch.apply(_ref, params);
    };

    Synchronizer.prototype.save = function(object, options) {
      object.save();
      return this.resourceClient.save(object, options);
    };

    Synchronizer.prototype.execute = function() {
      var params, _ref;
      params = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
      return (_ref = this.resourceClient).execute.apply(_ref, params);
    };

    Synchronizer.prototype.request = function() {
      var params, _ref;
      params = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
      return (_ref = this.resourceClient).request.apply(_ref, params);
    };

    Synchronizer.prototype.removeObjectsNotInList = function(collection, ids, scope) {
      var isInList, uri, uris, _i, _len, _results;
      uris = this.appContext.allURIs(collection, scope);
      _results = [];
      for (_i = 0, _len = uris.length; _i < _len; _i++) {
        uri = uris[_i];
        isInList = ids.indexOf(uri.id) !== -1;
        if (!isInList) {
          _results.push(this.appContext.destroy(uri));
        } else {
          _results.push(void 0);
        }
      }
      return _results;
    };

    Synchronizer.prototype.setAuthKey = function(key) {
      return this.authKey = key;
    };

    Synchronizer.prototype.hasAuthKey = function() {
      return (this.authKey != null) && this.authKey !== "";
    };

    Synchronizer.prototype.didAuth = function(content) {
      this.trigger("auth_success");
      return this.getChanges();
    };

    Synchronizer.prototype.didFailAuth = function(content) {
      return this.trigger("auth_fail");
    };

    return Synchronizer;

  })(Spine.Module);

  module.exports = Synchronizer;

}).call(this);
