// Generated by CoffeeScript 1.3.1
(function() {
  var assert, pluralize;

  assert = function(expression, message) {
    if (!expression) {
      throw message;
    }
  };

  pluralize = function(word) {
    if (word.match(/y$/)) {
      return word.replace(/y$/, 'ies');
    } else {
      return word + 's';
    }
  };

  module.exports = {
    assert: assert,
    pluralize: pluralize
  };

}).call(this);
