// Generated by CoffeeScript 1.3.3
(function() {
  var assert;

  assert = function(expression, message) {
    if (!expression) {
      throw message;
    }
  };

  module.exports = {
    assert: assert
  };

}).call(this);
